version: "3.3"
services:
  ts-vaultwarden:
    image: tailscale/tailscale:latest
    hostname: vaultwarden
    container_name: ts-vaultwarden
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/config.json
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - ${PWD}/tailscale/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped


  web:
    image: nginx
    container_name: nginx-vaultwarden
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ${PWD}/tailscale/state/certs/:/etc/letsencrypt/:ro
    environment:
      - NGINX_HOST=vaultwarden.dog-chameleon.ts.net
      - NGINX_PORT=443
    network_mode: service:ts-vaultwarden
    depends_on:
      - ts-vaultwarden

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - ROCKET_PORT=8080
    volumes:
      - ./_data:/data/
    devices:
      - /dev/dri:/dev/dri
    network_mode: service:ts-vaultwarden
    depends_on:
      - ts-vaultwarden
