version: '3'

services:
  vaultwarden:
    container_name: bitwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/Bitwarden/_data/:/data/
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:3012:3012
    environment:
      - ADMIN_TOKEN=YourReallyStrongAdminTokenHere
